# Generated by Django 4.1.2 on 2022-11-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='atractivos',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='detalle_cada_parada',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='lista_detalle_parada',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='recorrido',
        ),
        migrations.DeleteModel(
            name='Atractivo',
        ),
        migrations.DeleteModel(
            name='Chofer',
        ),
        migrations.DeleteModel(
            name='DetalleCadaParada',
        ),
        migrations.DeleteModel(
            name='Parada',
        ),
        migrations.DeleteModel(
            name='Recorrido',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
