# Generated by Django 4.1.2 on 2022-11-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atractivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallecadaparada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recorrido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={},
        ),
    ]
