# Generated by Django 4.1.2 on 2022-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_parada_atractivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
