# Generated by Django 4.1.2 on 2022-11-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_parada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCadaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField(blank=True, null=True)),
                ('conexion', models.IntegerField(blank=True, null=True)),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.parada')),
            ],
        ),
    ]
