# Generated by Django 4.1.2 on 2022-11-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_detallecadaparada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('duracion_aprox', models.IntegerField(blank=True, null=True)),
                ('frecuencia', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('lista_detalle_parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.detallecadaparada')),
            ],
        ),
    ]
