# Generated by Django 4.1.2 on 2022-11-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='fecha_compra',
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='frecuencia',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
