# Generated by Django 4.1.2 on 2022-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_remove_chofer_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
