# Generated by Django 4.1.2 on 2022-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_recorrido_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
