# Generated by Django 4.1.2 on 2022-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_alter_bus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
