# Generated by Django 4.1.2 on 2022-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_bus_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_unidad',
            field=models.IntegerField(),
        ),
    ]
