# Generated by Django 4.1.2 on 2022-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_bus_estado_alter_bus_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
