# Generated by Django 4.1.2 on 2022-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_alter_bus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_unidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
