# Generated by Django 4.1.2 on 2022-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_alter_bus_fecha_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='foto',
        ),
        migrations.AddField(
            model_name='parada',
            name='image_parada',
            field=models.ImageField(blank=True, null=True, upload_to='paradas/images/'),
        ),
    ]
