# Generated by Django 4.1.2 on 2022-12-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_remove_parada_foto_parada_image_parada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.CharField(blank=True, choices=[('En reparacion', 'En reparacion'), ('Listo', 'Listo')], max_length=50, null=True),
        ),
    ]
