# Generated by Django 4.1.2 on 2022-12-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_alter_bus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecadaparada',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.parada'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='lista_detalle_parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.detallecadaparada'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.bus'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.chofer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='recorrido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.recorrido'),
        ),
    ]
