# Generated by Django 4.1.3 on 2022-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_alter_detallecadaparada_parada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
